name: Build, Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: |
          rm -rf lib/chainlink
          rm -rf lib/forge-std
          
      - name: Install node js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install chainlink contracts via npm
        run: npm install @chainlink/contracts
          
      - name: Install tree and run command
        run: |
          sudo apt-get update && sudo apt-get install -y tree
          tree -L 5 node_modules/@chainlink/contracts/src/

      - name: Debug chainlink install
        run: |
          ls -la lib/chainlink/contracts/src/v0.8/functions/ || echo "Functions dir missing"
          ls -la lib/chainlink/contracts/src/v0.8/functions/v1_0_0/ || echo "v1_0_0 missing"
          cat lib/chainlink/contracts/src/v0.8/functions/v1_0_0/FunctionsClient.sol 2>/dev/null || echo "File not found"

      - name: Clean
        run: forge clean

      - name: Build contracts
        run: forge build --sizes

      - name: Run tests
        run: forge test -vvv

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      RPC_URL: https://sepolia.base.org  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Foundary
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

#      - name: Install dependencies
#        run: |
#          rm -rf lib/chainlink
#          rm -rf lib/forge-std
          
      - name: Install node js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install chainlink contracts via npm
        run: npm install @chainlink/contracts

      - name: Clean
        run: forge clean

      - name: Build contracts
        run: forge build --sizes


 

      - name: Deploy 
        run: |
          forge script script/DeployInsurance.s.sol:DeployInsurance \
            --rpc-url $RPC_URL \
            --private-key ${{ secrets.PRIVATE_KEY }} \
            --broadcast \
            --verify \
            --etherscan-api-key ${{ secrets.POLYGONSCAN_API_KEY }} \
