name: Build, Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
          RPC_URL: https://sepolia.base.org  
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable 

      - name: Install dependencies
        run: |
          rm -rf lib/chainlink
          rm -rf lib/forge-std
          
      - name: Install node js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

          
      - name: Install ESLint and HTML plugin
        working-directory: ./frontend
        run: npm install 

      - name: Lint javascript syntax in html files
        working-directory: ./frontend
        run: npm run lint

      - name: Install chainlink contracts via npm
        run: npm install @chainlink/contracts --no-save --no-package-lock

      - name: Symlink for foundry
        run: |
          mkdir -p lib/chainlink/contracts
          ln -s $(pwd)/node_modules/@chainlink/contracts lib/chainlink/contracts
          
      - name: Debug chainlink install
        run: |
          ls -la lib/chainlink/contracts/src/v0.8/functions/ || echo "Functions dir missing"
          ls -la lib/chainlink/contracts/src/v0.8/functions/v1_0_0/ || echo "v1_0_0 missing"
          cat lib/chainlink/contracts/src/v0.8/functions/v1_0_0/FunctionsClient.sol 2>/dev/null || echo "File not found"


 
      - name: Clean
        run: forge clean

      - name: Build contracts
        run: forge build --sizes

      - name: Show out/ directory structure build
        run: |
          ls -la out/ || echo "out/ folder missing completely!"
          find out/ -type f -name "*.json" || echo "No .json files found"


      - name: Run tests
        run: forge test -vvv

      - name: Generate ABI for frontend
        run: |
          jq '.abi' out/ParametricCropInsurance.sol/ParametricCropInsurance.json > abi_latest.json
          git config user.name "GitHub Actions"
          git add abi_latest.json
          git commit -m "CI:  commit latest abi [skip ci]" || echo "Nothing to commit"
          git push || echo "Push failed"



#      - name: Deploy 
#        run: |
#          forge script contracts/script/DeployInsurance.s.sol:DeployInsurance \
#            --rpc-url $RPC_URL \
#            --private-key ${{ secrets.PRIVATE_KEY }} \
#            --broadcast \
#            --verify \
#            --etherscan-api-key ${{ secrets.POLYGONSCAN_API_KEY }} \

  
